apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: nodejs-namespace
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - name: mongo-database
    port: 27017
    protocol: TCP
    targetPort: 27017
